apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-sentiment.fullname" . }}-svc
spec:
  selector:
    app: {{ include "ai-sentiment.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
